FROM ghcr.io/open-webui/mcpo:main

WORKDIR /app

COPY requirements.txt /tmp/requirements.txt

RUN . /app/.venv/bin/activate && \
    pip install --no-cache-dir -r /tmp/requirements.txt && \
    pip install --no-cache-dir -r /tmp/requirements.txt --target /usr/local/lib/python3.12/site-packages

RUN mkdir -p /rootPath

COPY config.json /rootPath
COPY tools /rootPath/tools
COPY templates /rootPath/templates
COPY functions /rootPath/functions

EXPOSE 8000

ENTRYPOINT []

CMD ["/app/.venv/bin/mcpo", "--type", "http", "--host", "0.0.0.0", "--port", "8000", "--config", "/rootPath/config.json", "--api-key", "${MCPO_API_KEY:-top-secret}"]

