name: Build & Push GHCR images

on:
  push:
    branches: [ master, main, dev ]
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: file-export-server
            context: LLM_Export/docker/file_server
            dockerfile: LLM_Export/docker/file_server/dockerfile.server
            image: ghcr.io/${{ github.repository_owner }}/owui-file-export-server
          - name: mcpo
            context: LLM_Export/docker/mcpo
            dockerfile: LLM_Export/docker/mcpo/dockerfile
            image: ghcr.io/${{ github.repository_owner }}/owui-mcpo
          - name: sse_http
            context: LLM_Export/docker/sse_http
            dockerfile: LLM_Export/docker/sse_http/dockerfile
            image: ghcr.io/${{ github.repository_owner }}/file-gen-sse-http
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Sanity check paths
        run: |
          pwd
          ls -la
          echo "---- LLM_Export ----"
          ls -la LLM_Export || true
          ls -la LLM_Export/docker || true
          ls -la LLM_Export/docker/file_server || true
          ls -la LLM_Export/docker/mcpo || true
          ls -la LLM_Export/docker/sse_http || true

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short
            type=ref,event=tag
            type=raw,value=dev-latest,enable=${{github.ref == 'refs/heads/dev'}}

      - name: Build & Push (${{ matrix.name }})
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
